# Generated by Django 4.2.13 on 2026-04-23 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Topshiriq nomi')),
                ('description', models.TextField(verbose_name='Topshiriq matni')),
                ('assignment_type', models.CharField(choices=[('amaliy', "Amaliy mashg'ulot"), ('mustaqil', "Mustaqil ta'lim"), ('oraliq', 'Oraliq nazorat')], default='amaliy', max_length=10, verbose_name='Tur')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Muddati')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, verbose_name='Maksimal urinish soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='groups.group', verbose_name='Guruh')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Test nomi')),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='Vaqt chegarasi (daqiqa)')),
                ('pass_score', models.PositiveSmallIntegerField(default=60, verbose_name="O'tish bali (%)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='groups.group', verbose_name='Guruh')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Ball (%)')),
                ('grade', models.IntegerField(blank=True, choices=[(2, 'Qoniqarsiz (2)'), (3, 'Qoniqarli (3)'), (4, 'Yaxshi (4)'), (5, "A'lo (5)")], null=True, verbose_name='Baho')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test urinishi',
                'verbose_name_plural': 'Test urinishlari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Matn javobi')),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Yuklangan fayl')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('grade', models.IntegerField(blank=True, choices=[(2, 'Qoniqarsiz (2)'), (3, 'Qoniqarli (3)'), (4, 'Yaxshi (4)'), (5, "A'lo (5)")], null=True, verbose_name='Baho')),
                ('feedback', models.TextField(blank=True, verbose_name="O'qituvchi izohi")),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.assignment', verbose_name='Topshiriq')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name="Baholagan o'qituvchi")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Topshiriq javobi',
                'verbose_name_plural': 'Topshiriq javoblari',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Tartib')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_grade', models.IntegerField(blank=True, null=True)),
                ('test_grade', models.IntegerField(blank=True, null=True)),
                ('overall_grade', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='courses.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': "Talaba o'zlashtiruvi",
                'verbose_name_plural': "Talaba o'zlashtirishlari",
                'ordering': ['topic__order_number'],
                'unique_together': {('student', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.testattempt', verbose_name='Urinish')),
                ('chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.choice', verbose_name='Tanlangan javob')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question', verbose_name='Savol')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
