# Generated by Django 4.2.13 on 2026-04-23 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('M1', 'M1: Abstrakt tuzilmalar. Algoritmlar tahlili'), ('M2', 'M2: Rekursiv algoritmlar'), ('M3', 'M3: Qidiruv algoritmlari. Xeshlash'), ('M4', 'M4: Saralash algoritmlari'), ('M5', "M5: Massivlar. Bog'langan ro'yxatlar"), ('M6', 'M6: Navbat, Stek va Dek'), ('M7', "M7: Daraxtsimon ma'lumotlar tuzilmalari"), ('M8', 'M8: Binar qidiruv daraxti. AVL daraxti'), ('M9', 'M9: Heap tree'), ('M10', 'M10: Graflar bilan ishlash algoritmlari'), ('M11', 'M11: BFS va DFS algoritmlar'), ('M12', "M12: Eng qisqa yo'l algoritmlari")], max_length=5, unique=True, verbose_name='Mavzu kodi')),
                ('title', models.CharField(max_length=200, verbose_name='Mavzu nomi')),
                ('description', models.TextField(blank=True, verbose_name='Qisqacha tavsif')),
                ('order_number', models.PositiveSmallIntegerField(verbose_name='Tartib raqami')),
                ('lecture_content', models.TextField(blank=True, verbose_name='Dars matni (HTML/Markdown)')),
                ('pseudo_code', models.TextField(blank=True, verbose_name='Psevdokod')),
                ('real_code', models.TextField(blank=True, verbose_name='Haqiqiy kod')),
                ('code_language', models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('python', 'Python')], default='cpp', max_length=20, verbose_name='Kod tili')),
                ('visualization_type', models.CharField(choices=[('none', "Yo'q"), ('bst', 'BST'), ('avl', 'AVL daraxti'), ('heap', 'Heap Tree'), ('bfs', 'BFS'), ('dfs', 'DFS'), ('sort', 'Saralash'), ('search', 'Qidiruv')], default='none', max_length=30, verbose_name='Vizualizatsiya')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL (YouTube/Vimeo)')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='topics/pdfs/', verbose_name='PDF/Slayd fayl')),
                ('is_published', models.BooleanField(default=False, verbose_name='Nashr qilingan')),
                ('lecture_duration', models.PositiveSmallIntegerField(default=80, verbose_name='Dars davomiyligi (daqiqa)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topics', to=settings.AUTH_USER_MODEL, verbose_name="Yaratgan o'qituvchi")),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Qulflangan'), ('unlocked', 'Ochilgan'), ('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan')], default='locked', max_length=15, verbose_name='Holat')),
                ('lesson_viewed', models.BooleanField(default=False, verbose_name="Dars ko'rildi")),
                ('lesson_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progresses', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progresses', to='courses.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Mavzu holati',
                'verbose_name_plural': 'Mavzu holatlari',
                'ordering': ['topic__order_number'],
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
