"""
apps/courses/management/commands/seed_topics.py

Sillabus asosida 12 ta MTA mavzusini bazaga kiritish.
Ishlatish: python manage.py seed_topics
"""

from django.core.management.base import BaseCommand
from apps.courses.models import Topic, TOPIC_ORDER


# Sillabus asosida 12 ta mavzu ma'lumotlari
MTA_TOPICS = [
    {
        'code': 'M1',
        'title': "Ma'lumotlarning abstrakt tuzilmalari. Algoritmlarni ishlab chiqish va tahlil qilish",
        'description': (
            "Ma'lumotlar tuzilmasi va algoritmlar faniga kirish. "
            "Abstrakt ma'lumotlar modeli, algoritmlarning murakkablik tahlili, "
            "Big-O notatsiyasi va ma'lumotlar turlarining klassifikatsiyasi."
        ),
        'pseudo_code': (
            "ALGORITHM AnalyzeComplexity(n)\n"
            "BEGIN\n"
            "    // O(1) - doimiy vaqt\n"
            "    result := n * 2\n"
            "\n"
            "    // O(n) - chiziqli vaqt\n"
            "    FOR i := 1 TO n DO\n"
            "        process(i)\n"
            "    END FOR\n"
            "\n"
            "    // O(n^2) - kvadratik vaqt\n"
            "    FOR i := 1 TO n DO\n"
            "        FOR j := 1 TO n DO\n"
            "            process(i, j)\n"
            "        END FOR\n"
            "    END FOR\n"
            "END"
        ),
        'real_code': (
            "// MTA — M1: Ma'lumotlar tuzilmasi va algoritmlar tahlili\n"
            "// Muallif: Madaminov Uktamjon | Urganch DU\n"
            "// VSCode'da ishlatish: g++ m1_intro.cpp -o m1 && ./m1\n\n"
            "#include <iostream>\n"
            "#include <vector>\n"
            "#include <chrono>\n"
            "using namespace std;\n"
            "using namespace chrono;\n\n"
            "// O(1) — Doimiy vaqt murakkabligi\n"
            "int constantTime(int n) {\n"
            "    return n * 2;  // Har doim 1 amal\n"
            "}\n\n"
            "// O(n) — Chiziqli murakkablik\n"
            "int linearTime(vector<int>& arr) {\n"
            "    int sum = 0;\n"
            "    for (int x : arr) {  // n marta takrorlanadi\n"
            "        sum += x;\n"
            "    }\n"
            "    return sum;\n"
            "}\n\n"
            "// O(n^2) — Kvadratik murakkablik\n"
            "void quadraticTime(vector<int>& arr) {\n"
            "    int n = arr.size();\n"
            "    for (int i = 0; i < n; i++) {       // n marta\n"
            "        for (int j = 0; j < n; j++) {   // har biri uchun n marta\n"
            "            // Jami: n * n = n^2 amal\n"
            "            cout << arr[i] * arr[j] << \" \";\n"
            "        }\n"
            "    }\n"
            "}\n\n"
            "int main() {\n"
            "    vector<int> data = {5, 3, 8, 1, 9, 2, 7, 4, 6};\n"
            "\n"
            "    cout << \"O(1): \" << constantTime(10) << endl;\n"
            "    cout << \"O(n) yig'indisi: \" << linearTime(data) << endl;\n\n"
            "    cout << \"Big-O tahlili:\" << endl;\n"
            "    cout << \"n=10 uchun: O(1)=1, O(n)=10, O(n^2)=100, O(2^n)=1024\" << endl;\n\n"
            "    return 0;\n"
            "}"
        ),
        'code_language': 'cpp',
        'visualization_type': 'none',
        'lecture_duration': 80,
    },
    {
        'code': 'M2',
        'title': "Rekursiv algoritmlar. Ularning tahlili",
        'description': (
            "Rekursiya tushunchasi, rekursiv algoritmlarning ishlash prinsipi, "
            "to'g'ridan-to'g'ri va bilvosita rekursiya. "
            "Rekursiyani iteratsiya bilan solishtirish. Stek overflow."
        ),
        'pseudo_code': (
            "ALGORITHM Factorial(n)\n"
            "BEGIN\n"
            "    IF n <= 1 THEN\n"
            "        RETURN 1          // Asosiy holat (base case)\n"
            "    ELSE\n"
            "        RETURN n * Factorial(n - 1)  // Rekursiv chaqiruv\n"
            "    END IF\n"
            "END\n\n"
            "ALGORITHM Fibonacci(n)\n"
            "BEGIN\n"
            "    IF n <= 1 THEN RETURN n\n"
            "    RETURN Fibonacci(n-1) + Fibonacci(n-2)\n"
            "END"
        ),
        'real_code': (
            "// MTA — M2: Rekursiv algoritmlar\n"
            "// Muallif: Madaminov Uktamjon | Urganch DU\n"
            "// VSCode: g++ m2_recursion.cpp -o m2 && ./m2\n\n"
            "#include <iostream>\n"
            "#include <map>\n"
            "using namespace std;\n\n"
            "// 1. Faktorial — klassik rekursiya\n"
            "long long factorial(int n) {\n"
            "    if (n <= 1) return 1;           // Asosiy holat\n"
            "    return n * factorial(n - 1);    // Rekursiv qadam\n"
            "}\n\n"
            "// 2. Fibonacci — sodda rekursiya (O(2^n) — sekin!)\n"
            "int fibSlow(int n) {\n"
            "    if (n <= 1) return n;\n"
            "    return fibSlow(n-1) + fibSlow(n-2);\n"
            "}\n\n"
            "// 3. Fibonacci — Memoizatsiya bilan (O(n) — tez!)\n"
            "map<int,long long> memo;\n"
            "long long fibFast(int n) {\n"
            "    if (n <= 1) return n;\n"
            "    if (memo.count(n)) return memo[n];  // Keshdan olish\n"
            "    return memo[n] = fibFast(n-1) + fibFast(n-2);\n"
            "}\n\n"
            "// 4. Ikkilik qidiruv — rekursiv versiya\n"
            "int binarySearch(int arr[], int left, int right, int target) {\n"
            "    if (left > right) return -1;        // Topilmadi\n"
            "    int mid = left + (right - left) / 2;\n"
            "    if (arr[mid] == target) return mid;  // Topildi\n"
            "    if (arr[mid] < target)\n"
            "        return binarySearch(arr, mid+1, right, target);\n"
            "    return binarySearch(arr, left, mid-1, target);\n"
            "}\n\n"
            "int main() {\n"
            "    cout << \"5! = \" << factorial(5) << endl;   // 120\n"
            "    cout << \"Fib(10) = \" << fibFast(10) << endl; // 55\n\n"
            "    int arr[] = {1, 3, 5, 7, 9, 11, 13, 15};\n"
            "    int n = sizeof(arr)/sizeof(arr[0]);\n"
            "    cout << \"7 indeksi: \" << binarySearch(arr, 0, n-1, 7) << endl; // 3\n\n"
            "    return 0;\n"
            "}"
        ),
        'code_language': 'cpp',
        'visualization_type': 'none',
        'lecture_duration': 80,
    },
    {
        'code': 'M3',
        'title': "Qidiruv algoritmlari va uning vazifasi. Chiziqli va Binar qidiruv. Xeshlash",
        'description': (
            "Chiziqli qidiruv O(n), binar qidiruv O(log n). "
            "Xesh jadval, xesh funksiyalar, kolliziyalar va ularni hal qilish usullari. "
            "Samaradorlikni tahlil qilish."
        ),
        'pseudo_code': (
            "ALGORITHM LinearSearch(arr, n, target)\n"
            "BEGIN\n"
            "    FOR i := 0 TO n-1 DO\n"
            "        IF arr[i] = target THEN\n"
            "            RETURN i\n"
            "        END IF\n"
            "    END FOR\n"
            "    RETURN -1\n"
            "END\n\n"
            "ALGORITHM BinarySearch(arr, left, right, target)\n"
            "BEGIN\n"
            "    WHILE left <= right DO\n"
            "        mid := (left + right) / 2\n"
            "        IF arr[mid] = target THEN RETURN mid\n"
            "        ELSE IF arr[mid] < target THEN left := mid + 1\n"
            "        ELSE right := mid - 1\n"
            "    END WHILE\n"
            "    RETURN -1\n"
            "END\n\n"
            "ALGORITHM HashInsert(table, key, value)\n"
            "BEGIN\n"
            "    index := hash(key) MOD tableSize\n"
            "    table[index] := value\n"
            "END"
        ),
        'real_code': (
            "// MTA — M3: Qidiruv algoritmlari va Xeshlash\n"
            "// Muallif: Madaminov Uktamjon | Urganch DU\n"
            "// VSCode: g++ m3_search.cpp -o m3 && ./m3\n\n"
            "#include <iostream>\n"
            "#include <vector>\n"
            "#include <unordered_map>\n"
            "using namespace std;\n\n"
            "// 1. Chiziqli qidiruv — O(n)\n"
            "int linearSearch(vector<int>& arr, int target) {\n"
            "    for (int i = 0; i < arr.size(); i++) {\n"
            "        if (arr[i] == target) return i;  // Topildi\n"
            "    }\n"
            "    return -1;  // Topilmadi\n"
            "}\n\n"
            "// 2. Binar qidiruv — O(log n) — massiv tartiblangan bo'lishi shart!\n"
            "int binarySearch(vector<int>& arr, int target) {\n"
            "    int left = 0, right = arr.size() - 1;\n"
            "    while (left <= right) {\n"
            "        int mid = left + (right - left) / 2;  // Overflow oldini olish\n"
            "        if (arr[mid] == target) return mid;\n"
            "        else if (arr[mid] < target) left = mid + 1;\n"
            "        else right = mid - 1;\n"
            "    }\n"
            "    return -1;\n"
            "}\n\n"
            "// 3. Xesh jadval — unordered_map orqali\n"
            "// O(1) o'rtacha, O(n) eng yomon holat\n"
            "void hashExample() {\n"
            "    unordered_map<string, int> phoneBook;\n"
            "\n"
            "    // Qo'shish — O(1)\n"
            "    phoneBook[\"Ali\"] = 901234567;\n"
            "    phoneBook[\"Vali\"] = 997654321;\n"
            "    phoneBook[\"Zafar\"] = 903216547;\n"
            "\n"
            "    // Qidirish — O(1)\n"
            "    string name = \"Ali\";\n"
            "    if (phoneBook.count(name)) {\n"
            "        cout << name << \": \" << phoneBook[name] << endl;\n"
            "    }\n"
            "\n"
            "    // O'chirish — O(1)\n"
            "    phoneBook.erase(\"Vali\");\n"
            "}\n\n"
            "// 4. Oddiy xesh funksiya\n"
            "int simpleHash(string key, int tableSize) {\n"
            "    int hash = 0;\n"
            "    for (char c : key) {\n"
            "        hash = (hash * 31 + c) % tableSize;\n"
            "    }\n"
            "    return hash;\n"
            "}\n\n"
            "int main() {\n"
            "    vector<int> arr = {2, 5, 8, 12, 16, 23, 38, 56, 72, 91};\n\n"
            "    cout << \"Chiziqli qidiruv (23): indeks = \"\n"
            "         << linearSearch(arr, 23) << endl;  // 5\n"
            "    cout << \"Binar qidiruv (23):   indeks = \"\n"
            "         << binarySearch(arr, 23) << endl;  // 5\n\n"
            "    hashExample();\n\n"
            "    cout << \"'Ali' xesh kodi (size=10): \"\n"
            "         << simpleHash(\"Ali\", 10) << endl;\n\n"
            "    return 0;\n"
            "}"
        ),
        'code_language': 'cpp',
        'visualization_type': 'search',
        'lecture_duration': 80,
    },
    {
        'code': 'M4',
        'title': "Ma'lumotlarni saralash algoritmlari. Qat'iy va yaxshilangan usullar",
        'description': (
            "Saralashning qat'iy usullari: Bubble Sort, Selection Sort, Insertion Sort. "
            "Yaxshilangan usullar: Merge Sort O(n log n), Quick Sort. "
            "Saralash algoritmlarini solishtirish va samaradorlik tahlili."
        ),
        'pseudo_code': (
            "ALGORITHM BubbleSort(arr, n)\n"
            "BEGIN\n"
            "    FOR i := 0 TO n-1 DO\n"
            "        FOR j := 0 TO n-i-2 DO\n"
            "            IF arr[j] > arr[j+1] THEN\n"
            "                SWAP(arr[j], arr[j+1])\n"
            "            END IF\n"
            "        END FOR\n"
            "    END FOR\n"
            "END\n\n"
            "ALGORITHM MergeSort(arr, left, right)\n"
            "BEGIN\n"
            "    IF left < right THEN\n"
            "        mid := (left + right) / 2\n"
            "        MergeSort(arr, left, mid)\n"
            "        MergeSort(arr, mid+1, right)\n"
            "        Merge(arr, left, mid, right)\n"
            "    END IF\n"
            "END"
        ),
        'real_code': (
            "// MTA — M4: Saralash algoritmlari\n"
            "// Muallif: Madaminov Uktamjon | Urganch DU\n"
            "// VSCode: g++ m4_sorting.cpp -o m4 && ./m4\n\n"
            "#include <iostream>\n"
            "#include <vector>\n"
            "#include <algorithm>\n"
            "using namespace std;\n\n"
            "void printArr(vector<int>& arr) {\n"
            "    for (int x : arr) cout << x << \" \";\n"
            "    cout << endl;\n"
            "}\n\n"
            "// 1. Bubble Sort — O(n^2) — eng sekin, tushunish oson\n"
            "void bubbleSort(vector<int>& arr) {\n"
            "    int n = arr.size();\n"
            "    for (int i = 0; i < n - 1; i++) {\n"
            "        bool swapped = false;\n"
            "        for (int j = 0; j < n - i - 1; j++) {\n"
            "            if (arr[j] > arr[j+1]) {\n"
            "                swap(arr[j], arr[j+1]);\n"
            "                swapped = true;\n"
            "            }\n"
            "        }\n"
            "        if (!swapped) break;  // Optimizatsiya\n"
            "    }\n"
            "}\n\n"
            "// 2. Selection Sort — O(n^2)\n"
            "void selectionSort(vector<int>& arr) {\n"
            "    int n = arr.size();\n"
            "    for (int i = 0; i < n - 1; i++) {\n"
            "        int minIdx = i;\n"
            "        for (int j = i + 1; j < n; j++)\n"
            "            if (arr[j] < arr[minIdx]) minIdx = j;\n"
            "        swap(arr[i], arr[minIdx]);\n"
            "    }\n"
            "}\n\n"
            "// 3. Merge Sort — O(n log n) — samarali\n"
            "void merge(vector<int>& arr, int l, int m, int r) {\n"
            "    vector<int> L(arr.begin()+l, arr.begin()+m+1);\n"
            "    vector<int> R(arr.begin()+m+1, arr.begin()+r+1);\n"
            "    int i = 0, j = 0, k = l;\n"
            "    while (i < L.size() && j < R.size())\n"
            "        arr[k++] = (L[i] <= R[j]) ? L[i++] : R[j++];\n"
            "    while (i < L.size()) arr[k++] = L[i++];\n"
            "    while (j < R.size()) arr[k++] = R[j++];\n"
            "}\n"
            "void mergeSort(vector<int>& arr, int l, int r) {\n"
            "    if (l < r) {\n"
            "        int m = l + (r - l) / 2;\n"
            "        mergeSort(arr, l, m);\n"
            "        mergeSort(arr, m+1, r);\n"
            "        merge(arr, l, m, r);\n"
            "    }\n"
            "}\n\n"
            "// 4. Quick Sort — O(n log n) o'rtacha\n"
            "int partition(vector<int>& arr, int low, int high) {\n"
            "    int pivot = arr[high];\n"
            "    int i = low - 1;\n"
            "    for (int j = low; j < high; j++)\n"
            "        if (arr[j] <= pivot) swap(arr[++i], arr[j]);\n"
            "    swap(arr[i+1], arr[high]);\n"
            "    return i + 1;\n"
            "}\n"
            "void quickSort(vector<int>& arr, int low, int high) {\n"
            "    if (low < high) {\n"
            "        int pi = partition(arr, low, high);\n"
            "        quickSort(arr, low, pi-1);\n"
            "        quickSort(arr, pi+1, high);\n"
            "    }\n"
            "}\n\n"
            "int main() {\n"
            "    vector<int> a1 = {64, 34, 25, 12, 22, 11, 90};\n"
            "    vector<int> a2 = a1, a3 = a1, a4 = a1;\n\n"
            "    bubbleSort(a1); cout << \"Bubble: \"; printArr(a1);\n"
            "    selectionSort(a2); cout << \"Select: \"; printArr(a2);\n"
            "    mergeSort(a3, 0, a3.size()-1); cout << \"Merge:  \"; printArr(a3);\n"
            "    quickSort(a4, 0, a4.size()-1); cout << \"Quick:  \"; printArr(a4);\n\n"
            "    return 0;\n"
            "}"
        ),
        'code_language': 'cpp',
        'visualization_type': 'sort',
        'lecture_duration': 80,
    },
    {
        'code': 'M5',
        'title': "Statik va dinamik massivlar. Chiziqli bog'langan ro'yxatlar",
        'description': (
            "Statik massiv vs vektor. Bir va ikki bog'lamli ro'yxatlar (Linked List). "
            "Tugun (node) tushunchasi, element qo'shish, o'chirish va qidirish algoritmlari."
        ),
        'pseudo_code': (
            "STRUCTURE Node\n"
            "    data: INTEGER\n"
            "    next: POINTER to Node\n"
            "END STRUCTURE\n\n"
            "ALGORITHM InsertAtFront(head, value)\n"
            "BEGIN\n"
            "    newNode := CREATE Node(value)\n"
            "    newNode.next := head\n"
            "    head := newNode\n"
            "    RETURN head\n"
            "END\n\n"
            "ALGORITHM DeleteNode(head, value)\n"
            "BEGIN\n"
            "    IF head.data = value THEN\n"
            "        RETURN head.next\n"
            "    current := head\n"
            "    WHILE current.next != NULL DO\n"
            "        IF current.next.data = value THEN\n"
            "            current.next := current.next.next\n"
            "            RETURN head\n"
            "        END IF\n"
            "        current := current.next\n"
            "    END WHILE\n"
            "    RETURN head\n"
            "END"
        ),
        'real_code': (
            "// MTA — M5: Bog'langan ro'yxatlar (Linked List)\n"
            "// Muallif: Madaminov Uktamjon | Urganch DU\n"
            "// VSCode: g++ m5_linkedlist.cpp -o m5 && ./m5\n\n"
            "#include <iostream>\n"
            "using namespace std;\n\n"
            "// Tugun tuzilmasi\n"
            "struct Node {\n"
            "    int data;\n"
            "    Node* next;\n"
            "    Node(int val) : data(val), next(nullptr) {}\n"
            "};\n\n"
            "// Bir bog'lamli ro'yxat klassi\n"
            "class LinkedList {\n"
            "private:\n"
            "    Node* head;\n"
            "public:\n"
            "    LinkedList() : head(nullptr) {}\n\n"
            "    // Boshiga qo'shish — O(1)\n"
            "    void pushFront(int val) {\n"
            "        Node* node = new Node(val);\n"
            "        node->next = head;\n"
            "        head = node;\n"
            "    }\n\n"
            "    // Oxiriga qo'shish — O(n)\n"
            "    void pushBack(int val) {\n"
            "        Node* node = new Node(val);\n"
            "        if (!head) { head = node; return; }\n"
            "        Node* cur = head;\n"
            "        while (cur->next) cur = cur->next;\n"
            "        cur->next = node;\n"
            "    }\n\n"
            "    // O'chirish — O(n)\n"
            "    void remove(int val) {\n"
            "        if (!head) return;\n"
            "        if (head->data == val) {\n"
            "            Node* tmp = head;\n"
            "            head = head->next;\n"
            "            delete tmp;\n"
            "            return;\n"
            "        }\n"
            "        Node* cur = head;\n"
            "        while (cur->next && cur->next->data != val)\n"
            "            cur = cur->next;\n"
            "        if (cur->next) {\n"
            "            Node* tmp = cur->next;\n"
            "            cur->next = tmp->next;\n"
            "            delete tmp;\n"
            "        }\n"
            "    }\n\n"
            "    // Chiqarish\n"
            "    void print() {\n"
            "        Node* cur = head;\n"
            "        while (cur) {\n"
            "            cout << cur->data;\n"
            "            if (cur->next) cout << \" -> \";\n"
            "            cur = cur->next;\n"
            "        }\n"
            "        cout << \" -> NULL\" << endl;\n"
            "    }\n\n"
            "    // Xotira tozalash\n"
            "    ~LinkedList() {\n"
            "        while (head) {\n"
            "            Node* tmp = head;\n"
            "            head = head->next;\n"
            "            delete tmp;\n"
            "        }\n"
            "    }\n"
            "};\n\n"
            "int main() {\n"
            "    LinkedList list;\n"
            "    list.pushBack(10);\n"
            "    list.pushBack(20);\n"
            "    list.pushBack(30);\n"
            "    list.pushFront(5);\n"
            "    cout << \"Dastlabki: \"; list.print();\n\n"
            "    list.remove(20);\n"
            "    cout << \"20 o'chirildi: \"; list.print();\n\n"
            "    return 0;\n"
            "}"
        ),
        'code_language': 'cpp',
        'visualization_type': 'none',
        'lecture_duration': 80,
    },
    {
        'code': 'M6',
        'title': "Navbat, stek va dek tuzilmalari",
        'description': (
            "Stek (LIFO): push, pop, top. Navbat (FIFO): enqueue, dequeue. "
            "Dek (ikki tomonlama navbat). "
            "Massiv va bog'langan ro'yxat yordamida amalga oshirish. STL: stack, queue, deque."
        ),
        'pseudo_code': (
            "// STEK (Stack) — LIFO\n"
            "ALGORITHM StackPush(stack, value)\n"
            "BEGIN\n"
            "    IF stack.size >= MAX THEN ERROR 'Overflow'\n"
            "    stack.top := stack.top + 1\n"
            "    stack.data[stack.top] := value\n"
            "END\n\n"
            "ALGORITHM StackPop(stack)\n"
            "BEGIN\n"
            "    IF stack.top < 0 THEN ERROR 'Underflow'\n"
            "    value := stack.data[stack.top]\n"
            "    stack.top := stack.top - 1\n"
            "    RETURN value\n"
            "END\n\n"
            "// NAVBAT (Queue) — FIFO\n"
            "ALGORITHM Enqueue(queue, value)\n"
            "BEGIN\n"
            "    queue.rear := (queue.rear + 1) MOD MAX\n"
            "    queue.data[queue.rear] := value\n"
            "    queue.size := queue.size + 1\n"
            "END"
        ),
        'real_code': (
            "// MTA — M6: Stek, Navbat va Dek\n"
            "// Muallif: Madaminov Uktamjon | Urganch DU\n"
            "// VSCode: g++ m6_stack_queue.cpp -o m6 && ./m6\n\n"
            "#include <iostream>\n"
            "#include <stack>\n"
            "#include <queue>\n"
            "#include <deque>\n"
            "using namespace std;\n\n"
            "// 1. STL Stack (LIFO — Last In First Out)\n"
            "void stackDemo() {\n"
            "    cout << \"=== STEK (LIFO) ===\" << endl;\n"
            "    stack<int> st;\n"
            "    st.push(10); st.push(20); st.push(30);\n"
            "    cout << \"Yuqori element: \" << st.top() << endl;  // 30\n"
            "    while (!st.empty()) {\n"
            "        cout << st.top() << \" \";  // 30 20 10\n"
            "        st.pop();\n"
            "    }\n"
            "    cout << endl;\n"
            "}\n\n"
            "// 2. STL Queue (FIFO — First In First Out)\n"
            "void queueDemo() {\n"
            "    cout << \"=== NAVBAT (FIFO) ===\" << endl;\n"
            "    queue<string> q;\n"
            "    q.push(\"Ali\"); q.push(\"Vali\"); q.push(\"Zafar\");\n"
            "    cout << \"Navbatdagi birinchi: \" << q.front() << endl;  // Ali\n"
            "    while (!q.empty()) {\n"
            "        cout << q.front() << \" \";  // Ali Vali Zafar\n"
            "        q.pop();\n"
            "    }\n"
            "    cout << endl;\n"
            "}\n\n"
            "// 3. STL Deque (ikki tomonlama)\n"
            "void dequeDemo() {\n"
            "    cout << \"=== DEK ===\" << endl;\n"
            "    deque<int> dq;\n"
            "    dq.push_back(10);   // Oxiriga\n"
            "    dq.push_front(5);   // Boshiga\n"
            "    dq.push_back(20);\n"
            "    dq.push_front(1);\n"
            "    // 1 5 10 20\n"
            "    for (int x : dq) cout << x << \" \";\n"
            "    cout << endl;\n"
            "}\n\n"
            "// 4. Stek amaliy misol: qavslar tekshiruvi\n"
            "bool isBalanced(string s) {\n"
            "    stack<char> st;\n"
            "    for (char c : s) {\n"
            "        if (c=='(' || c=='[' || c=='{') st.push(c);\n"
            "        else if (c==')' || c==']' || c=='}') {\n"
            "            if (st.empty()) return false;\n"
            "            char top = st.top(); st.pop();\n"
            "            if ((c==')' && top!='(') ||\n"
            "                (c==']' && top!='[') ||\n"
            "                (c=='}' && top!='{')) return false;\n"
            "        }\n"
            "    }\n"
            "    return st.empty();\n"
            "}\n\n"
            "int main() {\n"
            "    stackDemo();\n"
            "    queueDemo();\n"
            "    dequeDemo();\n"
            "    cout << \"'({[]})' muvozanatlimi? \" << (isBalanced(\"({[]})\") ? \"Ha\" : \"Yoq\") << endl;\n"
            "    cout << \"'([)]' muvozanatlimi? \" << (isBalanced(\"([)]\") ? \"Ha\" : \"Yoq\") << endl;\n"
            "    return 0;\n"
            "}"
        ),
        'code_language': 'cpp',
        'visualization_type': 'none',
        'lecture_duration': 80,
    },
    {
        'code': 'M7',
        'title': "Daraxtsimon ma'lumotlar tuzilmalari",
        'description': (
            "Daraxt tushunchasi: ildiz, tugun, barg, chuqurlik, balandlik. "
            "Binar daraxt, ko'p tarmoqli daraxt. "
            "Daraxtni ko'rish usullari: preorder, inorder, postorder."
        ),
        'pseudo_code': (
            "STRUCTURE TreeNode\n"
            "    data: INTEGER\n"
            "    left: POINTER to TreeNode\n"
            "    right: POINTER to TreeNode\n"
            "END STRUCTURE\n\n"
            "// Inorder ko'rish (chap - ildiz - o'ng)\n"
            "ALGORITHM Inorder(node)\n"
            "BEGIN\n"
            "    IF node != NULL THEN\n"
            "        Inorder(node.left)\n"
            "        PRINT node.data\n"
            "        Inorder(node.right)\n"
            "    END IF\n"
            "END\n\n"
            "// Daraxt balandligi\n"
            "ALGORITHM Height(node)\n"
            "BEGIN\n"
            "    IF node = NULL THEN RETURN 0\n"
            "    leftH := Height(node.left)\n"
            "    rightH := Height(node.right)\n"
            "    RETURN 1 + MAX(leftH, rightH)\n"
            "END"
        ),
        'real_code': (
            "// MTA — M7: Daraxtsimon ma'lumotlar tuzilmalari\n"
            "// Muallif: Madaminov Uktamjon | Urganch DU\n"
            "// VSCode: g++ m7_tree.cpp -o m7 && ./m7\n\n"
            "#include <iostream>\n"
            "#include <queue>\n"
            "using namespace std;\n\n"
            "struct Node {\n"
            "    int data;\n"
            "    Node *left, *right;\n"
            "    Node(int val) : data(val), left(nullptr), right(nullptr) {}\n"
            "};\n\n"
            "// Preorder: ildiz -> chap -> o'ng\n"
            "void preorder(Node* root) {\n"
            "    if (!root) return;\n"
            "    cout << root->data << \" \";\n"
            "    preorder(root->left);\n"
            "    preorder(root->right);\n"
            "}\n\n"
            "// Inorder: chap -> ildiz -> o'ng (BST uchun tartiblangan)\n"
            "void inorder(Node* root) {\n"
            "    if (!root) return;\n"
            "    inorder(root->left);\n"
            "    cout << root->data << \" \";\n"
            "    inorder(root->right);\n"
            "}\n\n"
            "// Postorder: chap -> o'ng -> ildiz\n"
            "void postorder(Node* root) {\n"
            "    if (!root) return;\n"
            "    postorder(root->left);\n"
            "    postorder(root->right);\n"
            "    cout << root->data << \" \";\n"
            "}\n\n"
            "// Daraxt balandligi\n"
            "int height(Node* root) {\n"
            "    if (!root) return 0;\n"
            "    return 1 + max(height(root->left), height(root->right));\n"
            "}\n\n"
            "// Kenglik bo'yicha (BFS)\n"
            "void levelOrder(Node* root) {\n"
            "    if (!root) return;\n"
            "    queue<Node*> q;\n"
            "    q.push(root);\n"
            "    while (!q.empty()) {\n"
            "        Node* cur = q.front(); q.pop();\n"
            "        cout << cur->data << \" \";\n"
            "        if (cur->left)  q.push(cur->left);\n"
            "        if (cur->right) q.push(cur->right);\n"
            "    }\n"
            "}\n\n"
            "int main() {\n"
            "    //       1\n"
            "    //      / \\\n"
            "    //     2   3\n"
            "    //    / \\\n"
            "    //   4   5\n"
            "    Node* root = new Node(1);\n"
            "    root->left  = new Node(2);\n"
            "    root->right = new Node(3);\n"
            "    root->left->left  = new Node(4);\n"
            "    root->left->right = new Node(5);\n\n"
            "    cout << \"Preorder:    \"; preorder(root);   cout << endl;\n"
            "    cout << \"Inorder:     \"; inorder(root);    cout << endl;\n"
            "    cout << \"Postorder:   \"; postorder(root);  cout << endl;\n"
            "    cout << \"Level-order: \"; levelOrder(root); cout << endl;\n"
            "    cout << \"Balandlik: \" << height(root) << endl;\n\n"
            "    return 0;\n"
            "}"
        ),
        'code_language': 'cpp',
        'visualization_type': 'bst',
        'lecture_duration': 80,
    },
    {
        'code': 'M8',
        'title': "Binar qidiruv daraxti (BST). Muvozanatlangan daraxtlar. AVL daraxti",
        'description': (
            "BST: element qo'shish, qidirish, o'chirish O(log n) o'rtacha. "
            "Muvozanatlash zarurati, AVL daraxti: rotatsiya turlari (LL, RR, LR, RL). "
            "Balandlik farqi va muvozanatlash faktori."
        ),
        'pseudo_code': (
            "ALGORITHM BSTInsert(root, value)\n"
            "BEGIN\n"
            "    IF root = NULL THEN RETURN Node(value)\n"
            "    IF value < root.data THEN\n"
            "        root.left := BSTInsert(root.left, value)\n"
            "    ELSE IF value > root.data THEN\n"
            "        root.right := BSTInsert(root.right, value)\n"
            "    RETURN root\n"
            "END\n\n"
            "ALGORITHM AVLInsert(root, value)\n"
            "BEGIN\n"
            "    root := BSTInsert(root, value)\n"
            "    balance := Height(root.left) - Height(root.right)\n"
            "    IF balance > 1 THEN\n"
            "        IF value < root.left.data THEN\n"
            "            RETURN RotateRight(root)  // LL holat\n"
            "        ELSE\n"
            "            root.left := RotateLeft(root.left)\n"
            "            RETURN RotateRight(root)  // LR holat\n"
            "        END IF\n"
            "    // RR va RL holatlari ham shunga o'xshash\n"
            "    RETURN root\n"
            "END"
        ),
        'real_code': (
            "// MTA — M8: BST va AVL daraxti\n"
            "// Muallif: Madaminov Uktamjon | Urganch DU\n"
            "// VSCode: g++ m8_bst_avl.cpp -o m8 && ./m8\n\n"
            "#include <iostream>\n"
            "using namespace std;\n\n"
            "// ── BST ────────────────────────────────────────────\n"
            "struct BSTNode {\n"
            "    int data;\n"
            "    BSTNode *left, *right;\n"
            "    BSTNode(int v) : data(v), left(nullptr), right(nullptr) {}\n"
            "};\n\n"
            "BSTNode* bstInsert(BSTNode* root, int val) {\n"
            "    if (!root) return new BSTNode(val);\n"
            "    if (val < root->data) root->left  = bstInsert(root->left,  val);\n"
            "    else if (val > root->data) root->right = bstInsert(root->right, val);\n"
            "    return root;  // Takrorlangan qiymat qo'shilmaydi\n"
            "}\n\n"
            "BSTNode* bstSearch(BSTNode* root, int val) {\n"
            "    if (!root || root->data == val) return root;\n"
            "    if (val < root->data) return bstSearch(root->left, val);\n"
            "    return bstSearch(root->right, val);\n"
            "}\n\n"
            "// ── AVL ────────────────────────────────────────────\n"
            "struct AVLNode {\n"
            "    int data, height;\n"
            "    AVLNode *left, *right;\n"
            "    AVLNode(int v) : data(v), height(1), left(nullptr), right(nullptr) {}\n"
            "};\n\n"
            "int avlHeight(AVLNode* n) { return n ? n->height : 0; }\n"
            "int getBalance(AVLNode* n) {\n"
            "    return n ? avlHeight(n->left) - avlHeight(n->right) : 0;\n"
            "}\n\n"
            "AVLNode* rotateRight(AVLNode* y) {\n"
            "    AVLNode* x = y->left;\n"
            "    AVLNode* T = x->right;\n"
            "    x->right = y; y->left = T;\n"
            "    y->height = 1 + max(avlHeight(y->left), avlHeight(y->right));\n"
            "    x->height = 1 + max(avlHeight(x->left), avlHeight(x->right));\n"
            "    return x;\n"
            "}\n\n"
            "AVLNode* rotateLeft(AVLNode* x) {\n"
            "    AVLNode* y = x->right;\n"
            "    AVLNode* T = y->left;\n"
            "    y->left = x; x->right = T;\n"
            "    x->height = 1 + max(avlHeight(x->left), avlHeight(x->right));\n"
            "    y->height = 1 + max(avlHeight(y->left), avlHeight(y->right));\n"
            "    return y;\n"
            "}\n\n"
            "AVLNode* avlInsert(AVLNode* root, int val) {\n"
            "    if (!root) return new AVLNode(val);\n"
            "    if (val < root->data) root->left  = avlInsert(root->left, val);\n"
            "    else if (val > root->data) root->right = avlInsert(root->right, val);\n"
            "    else return root;\n"
            "    root->height = 1 + max(avlHeight(root->left), avlHeight(root->right));\n"
            "    int bal = getBalance(root);\n"
            "    if (bal > 1 && val < root->left->data)  return rotateRight(root); // LL\n"
            "    if (bal < -1 && val > root->right->data) return rotateLeft(root);  // RR\n"
            "    if (bal > 1 && val > root->left->data) {\n"
            "        root->left = rotateLeft(root->left); return rotateRight(root); // LR\n"
            "    }\n"
            "    if (bal < -1 && val < root->right->data) {\n"
            "        root->right = rotateRight(root->right); return rotateLeft(root); // RL\n"
            "    }\n"
            "    return root;\n"
            "}\n\n"
            "void inorder(BSTNode* r){if(!r)return;inorder(r->left);cout<<r->data<<\" \";inorder(r->right);}\n"
            "void avlInorder(AVLNode* r){if(!r)return;avlInorder(r->left);cout<<r->data<<\"(h\"<<r->height<<\") \";avlInorder(r->right);}\n\n"
            "int main() {\n"
            "    BSTNode* bst = nullptr;\n"
            "    for (int v : {50,30,70,20,40,60,80})\n"
            "        bst = bstInsert(bst, v);\n"
            "    cout << \"BST Inorder: \"; inorder(bst); cout << endl;\n\n"
            "    AVLNode* avl = nullptr;\n"
            "    for (int v : {30,20,10,25,40,50})\n"
            "        avl = avlInsert(avl, v);\n"
            "    cout << \"AVL Inorder: \"; avlInorder(avl); cout << endl;\n"
            "    cout << \"AVL Balans:  \" << getBalance(avl) << endl;\n\n"
            "    return 0;\n"
            "}"
        ),
        'code_language': 'cpp',
        'visualization_type': 'avl',
        'lecture_duration': 80,
    },
    {
        'code': 'M9',
        'title': "Heap tree ko'rinishidagi binar daraxtlar",
        'description': (
            "Max-Heap va Min-Heap tuzilmasi. Heap xossasi. "
            "Heapify algoritmi, element qo'shish va o'chirish. "
            "Heap Sort O(n log n). Priority Queue."
        ),
        'pseudo_code': (
            "// MAX-HEAP: har bir ota tugun bolalaridan katta\n"
            "ALGORITHM Heapify(arr, n, i)\n"
            "BEGIN\n"
            "    largest := i\n"
            "    left    := 2*i + 1\n"
            "    right   := 2*i + 2\n"
            "    IF left < n AND arr[left] > arr[largest] THEN\n"
            "        largest := left\n"
            "    IF right < n AND arr[right] > arr[largest] THEN\n"
            "        largest := right\n"
            "    IF largest != i THEN\n"
            "        SWAP(arr[i], arr[largest])\n"
            "        Heapify(arr, n, largest)\n"
            "    END IF\n"
            "END\n\n"
            "ALGORITHM HeapSort(arr, n)\n"
            "BEGIN\n"
            "    // Heap qurish\n"
            "    FOR i := n/2-1 DOWNTO 0 DO\n"
            "        Heapify(arr, n, i)\n"
            "    // Birma-bir elementlarni chiqarish\n"
            "    FOR i := n-1 DOWNTO 1 DO\n"
            "        SWAP(arr[0], arr[i])\n"
            "        Heapify(arr, i, 0)\n"
            "    END FOR\n"
            "END"
        ),
        'real_code': (
            "// MTA — M9: Heap Tree va Heap Sort\n"
            "// Muallif: Madaminov Uktamjon | Urganch DU\n"
            "// VSCode: g++ m9_heap.cpp -o m9 && ./m9\n\n"
            "#include <iostream>\n"
            "#include <vector>\n"
            "#include <queue>  // priority_queue uchun\n"
            "using namespace std;\n\n"
            "// Max-Heap uchun heapify\n"
            "void heapify(vector<int>& arr, int n, int i) {\n"
            "    int largest = i;\n"
            "    int left    = 2*i + 1;\n"
            "    int right   = 2*i + 2;\n\n"
            "    if (left < n && arr[left] > arr[largest])   largest = left;\n"
            "    if (right < n && arr[right] > arr[largest]) largest = right;\n\n"
            "    if (largest != i) {\n"
            "        swap(arr[i], arr[largest]);\n"
            "        heapify(arr, n, largest);  // Rekursiv tuzatish\n"
            "    }\n"
            "}\n\n"
            "// Heap Sort — O(n log n)\n"
            "void heapSort(vector<int>& arr) {\n"
            "    int n = arr.size();\n"
            "    // 1. Max-Heap qurish\n"
            "    for (int i = n/2 - 1; i >= 0; i--)\n"
            "        heapify(arr, n, i);\n"
            "    // 2. Eng kattani oxiriga surib chiqarish\n"
            "    for (int i = n - 1; i > 0; i--) {\n"
            "        swap(arr[0], arr[i]);  // Max -> oxir\n"
            "        heapify(arr, i, 0);   // Qolganini tuzatish\n"
            "    }\n"
            "}\n\n"
            "// STL Priority Queue (Max-Heap)\n"
            "void priorityQueueDemo() {\n"
            "    cout << \"=== Max Priority Queue ===\" << endl;\n"
            "    priority_queue<int> pq;\n"
            "    pq.push(30); pq.push(10); pq.push(50); pq.push(20);\n"
            "    while (!pq.empty()) {\n"
            "        cout << pq.top() << \" \";  // 50 30 20 10\n"
            "        pq.pop();\n"
            "    }\n"
            "    cout << endl;\n\n"
            "    // Min-Heap\n"
            "    cout << \"=== Min Priority Queue ===\" << endl;\n"
            "    priority_queue<int, vector<int>, greater<int>> minPQ;\n"
            "    minPQ.push(30); minPQ.push(10); minPQ.push(50);\n"
            "    while (!minPQ.empty()) {\n"
            "        cout << minPQ.top() << \" \";  // 10 30 50\n"
            "        minPQ.pop();\n"
            "    }\n"
            "    cout << endl;\n"
            "}\n\n"
            "int main() {\n"
            "    vector<int> arr = {12, 11, 13, 5, 6, 7};\n"
            "    cout << \"Dastlabki: \";\n"
            "    for (int x : arr) cout << x << \" \";\n"
            "    cout << endl;\n\n"
            "    heapSort(arr);\n"
            "    cout << \"Heap Sort: \";\n"
            "    for (int x : arr) cout << x << \" \";\n"
            "    cout << endl;\n\n"
            "    priorityQueueDemo();\n"
            "    return 0;\n"
            "}"
        ),
        'code_language': 'cpp',
        'visualization_type': 'heap',
        'lecture_duration': 80,
    },
    {
        'code': 'M10',
        'title': "Graflar bilan ishlash algoritmlari",
        'description': (
            "Graf tushunchasi: tugunlar (vertex) va qirralar (edge). "
            "Yo'naltirilgan va yo'naltirilmagan graflar. "
            "Grafni tasvirlash usullari: qo'shnilik matritsasi, qo'shnilik ro'yxati, yoylar ro'yxati."
        ),
        'pseudo_code': (
            "// Graf qo'shnilik ro'yxati sifatida\n"
            "STRUCTURE Graph\n"
            "    V: INTEGER         // Tugunlar soni\n"
            "    adj: LIST OF LISTS // Qo'shnilik ro'yxati\n"
            "END\n\n"
            "ALGORITHM AddEdge(graph, u, v)\n"
            "BEGIN\n"
            "    graph.adj[u].append(v)\n"
            "    graph.adj[v].append(u)  // Yo'naltirilmagan graf\n"
            "END\n\n"
            "// Qo'shnilik matritsasi\n"
            "ALGORITHM AddEdgeMatrix(matrix, u, v, weight)\n"
            "BEGIN\n"
            "    matrix[u][v] := weight\n"
            "    matrix[v][u] := weight  // Simmetrik\n"
            "END"
        ),
        'real_code': (
            "// MTA — M10: Graflar va ularni tasvirlash\n"
            "// Muallif: Madaminov Uktamjon | Urganch DU\n"
            "// VSCode: g++ m10_graph.cpp -o m10 && ./m10\n\n"
            "#include <iostream>\n"
            "#include <vector>\n"
            "#include <list>\n"
            "using namespace std;\n\n"
            "// Graf klassi — Qo'shnilik ro'yxati\n"
            "class Graph {\n"
            "    int V;  // Tugunlar soni\n"
            "    vector<list<int>> adj;\n"
            "public:\n"
            "    Graph(int v) : V(v), adj(v) {}\n\n"
            "    // Qirra qo'shish (yo'naltirilmagan)\n"
            "    void addEdge(int u, int v) {\n"
            "        adj[u].push_back(v);\n"
            "        adj[v].push_back(u);\n"
            "    }\n\n"
            "    // Qo'shnilik ro'yxatini chiqarish\n"
            "    void printAdjList() {\n"
            "        cout << \"Qo'shnilik ro'yxati:\" << endl;\n"
            "        for (int i = 0; i < V; i++) {\n"
            "            cout << i << \" -> \";\n"
            "            for (int v : adj[i]) cout << v << \" \";\n"
            "            cout << endl;\n"
            "        }\n"
            "    }\n"
            "    vector<list<int>>& getAdj() { return adj; }\n"
            "    int getV() { return V; }\n"
            "};\n\n"
            "// Qo'shnilik matritsasi\n"
            "void printAdjMatrix(int** mat, int V) {\n"
            "    cout << \"Qo'shnilik matritsasi:\" << endl;\n"
            "    cout << \"  \";\n"
            "    for (int i = 0; i < V; i++) cout << i << \" \";\n"
            "    cout << endl;\n"
            "    for (int i = 0; i < V; i++) {\n"
            "        cout << i << \" \";\n"
            "        for (int j = 0; j < V; j++)\n"
            "            cout << mat[i][j] << \" \";\n"
            "        cout << endl;\n"
            "    }\n"
            "}\n\n"
            "int main() {\n"
            "    // 5 tugunli graf: 0-1-2-3-4\n"
            "    Graph g(5);\n"
            "    g.addEdge(0, 1);\n"
            "    g.addEdge(0, 4);\n"
            "    g.addEdge(1, 2);\n"
            "    g.addEdge(1, 3);\n"
            "    g.addEdge(1, 4);\n"
            "    g.addEdge(2, 3);\n"
            "    g.addEdge(3, 4);\n"
            "    g.printAdjList();\n\n"
            "    // Qo'shnilik matritsasi\n"
            "    int V = 4;\n"
            "    int** mat = new int*[V];\n"
            "    for (int i = 0; i < V; i++) {\n"
            "        mat[i] = new int[V]();\n"
            "    }\n"
            "    mat[0][1] = mat[1][0] = 1;\n"
            "    mat[0][2] = mat[2][0] = 1;\n"
            "    mat[1][3] = mat[3][1] = 1;\n"
            "    mat[2][3] = mat[3][2] = 1;\n"
            "    printAdjMatrix(mat, V);\n\n"
            "    return 0;\n"
            "}"
        ),
        'code_language': 'cpp',
        'visualization_type': 'bfs',
        'lecture_duration': 80,
    },
    {
        'code': 'M11',
        'title': "Graflarda ko'ruv algoritmlari. BFS va DFS",
        'description': (
            "Eniga qarab qidiruv (BFS) — navbat asosida, O(V+E). "
            "Tubiga qarab qidiruv (DFS) — stek/rekursiya asosida, O(V+E). "
            "BFS va DFS taqqoslash, amaliy qo'llanishlar."
        ),
        'pseudo_code': (
            "ALGORITHM BFS(graph, start)\n"
            "BEGIN\n"
            "    visited := SET()\n"
            "    queue := QUEUE()\n"
            "    queue.enqueue(start)\n"
            "    visited.add(start)\n"
            "    WHILE queue != empty DO\n"
            "        v := queue.dequeue()\n"
            "        PRINT v\n"
            "        FOR each neighbor u of v DO\n"
            "            IF u NOT IN visited THEN\n"
            "                visited.add(u)\n"
            "                queue.enqueue(u)\n"
            "            END IF\n"
            "        END FOR\n"
            "    END WHILE\n"
            "END\n\n"
            "ALGORITHM DFS(graph, v, visited)\n"
            "BEGIN\n"
            "    visited.add(v)\n"
            "    PRINT v\n"
            "    FOR each neighbor u of v DO\n"
            "        IF u NOT IN visited THEN\n"
            "            DFS(graph, u, visited)\n"
            "        END IF\n"
            "    END FOR\n"
            "END"
        ),
        'real_code': (
            "// MTA — M11: BFS va DFS algoritmlari\n"
            "// Muallif: Madaminov Uktamjon | Urganch DU\n"
            "// VSCode: g++ m11_bfs_dfs.cpp -o m11 && ./m11\n\n"
            "#include <iostream>\n"
            "#include <vector>\n"
            "#include <queue>\n"
            "#include <stack>\n"
            "using namespace std;\n\n"
            "const int MAXV = 10;\n"
            "vector<int> adj[MAXV];\n"
            "bool visited[MAXV];\n\n"
            "void addEdge(int u, int v) {\n"
            "    adj[u].push_back(v);\n"
            "    adj[v].push_back(u);\n"
            "}\n\n"
            "// BFS — Kenglik bo'yicha qidiruv (navbat)\n"
            "void BFS(int start, int V) {\n"
            "    fill(visited, visited+V, false);\n"
            "    queue<int> q;\n"
            "    q.push(start);\n"
            "    visited[start] = true;\n"
            "    cout << \"BFS: \";\n"
            "    while (!q.empty()) {\n"
            "        int v = q.front(); q.pop();\n"
            "        cout << v << \" \";\n"
            "        for (int u : adj[v]) {\n"
            "            if (!visited[u]) {\n"
            "                visited[u] = true;\n"
            "                q.push(u);\n"
            "            }\n"
            "        }\n"
            "    }\n"
            "    cout << endl;\n"
            "}\n\n"
            "// DFS — Chuqurlik bo'yicha qidiruv (rekursiv)\n"
            "void DFSRecursive(int v) {\n"
            "    visited[v] = true;\n"
            "    cout << v << \" \";\n"
            "    for (int u : adj[v])\n"
            "        if (!visited[u]) DFSRecursive(u);\n"
            "}\n\n"
            "void DFS(int start, int V) {\n"
            "    fill(visited, visited+V, false);\n"
            "    cout << \"DFS: \";\n"
            "    DFSRecursive(start);\n"
            "    cout << endl;\n"
            "}\n\n"
            "// DFS — Iterativ (stek bilan)\n"
            "void DFSIterative(int start, int V) {\n"
            "    fill(visited, visited+V, false);\n"
            "    stack<int> st;\n"
            "    st.push(start);\n"
            "    cout << \"DFS (stek): \";\n"
            "    while (!st.empty()) {\n"
            "        int v = st.top(); st.pop();\n"
            "        if (!visited[v]) {\n"
            "            visited[v] = true;\n"
            "            cout << v << \" \";\n"
            "            for (int u : adj[v])\n"
            "                if (!visited[u]) st.push(u);\n"
            "        }\n"
            "    }\n"
            "    cout << endl;\n"
            "}\n\n"
            "int main() {\n"
            "    // Graf:\n"
            "    //  0 - 1 - 2\n"
            "    //  |   |   |\n"
            "    //  3 - 4   5\n"
            "    int V = 6;\n"
            "    addEdge(0,1); addEdge(0,3); addEdge(1,2);\n"
            "    addEdge(1,4); addEdge(2,5); addEdge(3,4);\n\n"
            "    BFS(0, V);\n"
            "    DFS(0, V);\n"
            "    DFSIterative(0, V);\n\n"
            "    return 0;\n"
            "}"
        ),
        'code_language': 'cpp',
        'visualization_type': 'dfs',
        'lecture_duration': 80,
    },
    {
        'code': 'M12',
        'title': "Graflarda eng qisqa yo'lni aniqlash algoritmlari. Floyd, Ford-Bellman, Dijkstra",
        'description': (
            "Dijkstra algoritmi — manfiy bo'lmagan og'irliklar uchun, O((V+E) log V). "
            "Floyd-Warshall — barcha juftlar orasidagi eng qisqa yo'l, O(V^3). "
            "Ford-Bellman — manfiy og'irliklar uchun, O(VE)."
        ),
        'pseudo_code': (
            "ALGORITHM Dijkstra(graph, source)\n"
            "BEGIN\n"
            "    dist[source] := 0\n"
            "    FOR all v != source: dist[v] := INFINITY\n"
            "    pq := PRIORITY_QUEUE {(0, source)}\n"
            "    WHILE pq != empty DO\n"
            "        (d, u) := pq.extractMin()\n"
            "        FOR each (u, v, w) in graph DO\n"
            "            IF dist[u] + w < dist[v] THEN\n"
            "                dist[v] := dist[u] + w\n"
            "                pq.insert(dist[v], v)\n"
            "            END IF\n"
            "        END FOR\n"
            "    END WHILE\n"
            "    RETURN dist\n"
            "END\n\n"
            "ALGORITHM FloydWarshall(dist, V)\n"
            "BEGIN\n"
            "    FOR k := 0 TO V-1 DO\n"
            "        FOR i := 0 TO V-1 DO\n"
            "            FOR j := 0 TO V-1 DO\n"
            "                IF dist[i][k] + dist[k][j] < dist[i][j] THEN\n"
            "                    dist[i][j] := dist[i][k] + dist[k][j]\n"
            "            END FOR\n"
            "        END FOR\n"
            "    END FOR\n"
            "END"
        ),
        'real_code': (
            "// MTA — M12: Eng qisqa yo'l algoritmlari\n"
            "// Muallif: Madaminov Uktamjon | Urganch DU\n"
            "// VSCode: g++ m12_shortest.cpp -o m12 && ./m12\n\n"
            "#include <iostream>\n"
            "#include <vector>\n"
            "#include <queue>\n"
            "#include <climits>\n"
            "using namespace std;\n\n"
            "typedef pair<int,int> pii;\n"
            "const int INF = INT_MAX;\n\n"
            "// ── Dijkstra algoritmi ────────────────────────────\n"
            "// Manfiy bo'lmagan og'irliklar uchun — O((V+E) log V)\n"
            "vector<int> dijkstra(int src, int V, vector<vector<pii>>& adj) {\n"
            "    vector<int> dist(V, INF);\n"
            "    priority_queue<pii, vector<pii>, greater<pii>> pq;\n"
            "    dist[src] = 0;\n"
            "    pq.push({0, src});\n"
            "    while (!pq.empty()) {\n"
            "        auto [d, u] = pq.top(); pq.pop();\n"
            "        if (d > dist[u]) continue;  // Eskirgan\n"
            "        for (auto [v, w] : adj[u]) {\n"
            "            if (dist[u] + w < dist[v]) {\n"
            "                dist[v] = dist[u] + w;\n"
            "                pq.push({dist[v], v});\n"
            "            }\n"
            "        }\n"
            "    }\n"
            "    return dist;\n"
            "}\n\n"
            "// ── Floyd-Warshall algoritmi ──────────────────────\n"
            "// Barcha juftlar — O(V^3)\n"
            "void floydWarshall(vector<vector<int>>& dist, int V) {\n"
            "    for (int k = 0; k < V; k++)\n"
            "        for (int i = 0; i < V; i++)\n"
            "            for (int j = 0; j < V; j++)\n"
            "                if (dist[i][k] != INF && dist[k][j] != INF)\n"
            "                    dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j]);\n"
            "}\n\n"
            "// ── Ford-Bellman algoritmi ────────────────────────\n"
            "// Manfiy og'irliklar uchun — O(VE)\n"
            "struct Edge { int u, v, w; };\n"
            "vector<int> bellmanFord(int src, int V, vector<Edge>& edges) {\n"
            "    vector<int> dist(V, INF);\n"
            "    dist[src] = 0;\n"
            "    for (int i = 0; i < V - 1; i++)\n"
            "        for (auto& e : edges)\n"
            "            if (dist[e.u] != INF && dist[e.u] + e.w < dist[e.v])\n"
            "                dist[e.v] = dist[e.u] + e.w;\n"
            "    return dist;\n"
            "}\n\n"
            "int main() {\n"
            "    // Graf: 5 tugun\n"
            "    int V = 5;\n"
            "    vector<vector<pii>> adj(V);\n"
            "    auto addEdge = [&](int u, int v, int w) {\n"
            "        adj[u].push_back({v, w});\n"
            "        adj[v].push_back({u, w});\n"
            "    };\n"
            "    addEdge(0,1,4); addEdge(0,2,1); addEdge(2,1,2);\n"
            "    addEdge(1,3,1); addEdge(2,3,5); addEdge(3,4,3);\n\n"
            "    auto d = dijkstra(0, V, adj);\n"
            "    cout << \"Dijkstra (0-dan):\" << endl;\n"
            "    for (int i = 0; i < V; i++)\n"
            "        cout << \"  0 -> \" << i << \" = \" << d[i] << endl;\n\n"
            "    // Floyd-Warshall\n"
            "    vector<vector<int>> fw(V, vector<int>(V, INF));\n"
            "    for (int i = 0; i < V; i++) fw[i][i] = 0;\n"
            "    fw[0][1]=4; fw[1][0]=4; fw[0][2]=1; fw[2][0]=1;\n"
            "    fw[2][1]=2; fw[1][2]=2; fw[1][3]=1; fw[3][1]=1;\n"
            "    fw[3][4]=3; fw[4][3]=3;\n"
            "    floydWarshall(fw, V);\n"
            "    cout << \"Floyd-Warshall 0->4: \" << fw[0][4] << endl;\n\n"
            "    return 0;\n"
            "}"
        ),
        'code_language': 'cpp',
        'visualization_type': 'bfs',
        'lecture_duration': 80,
    },
]


class Command(BaseCommand):
    help = "Sillabus asosida MTA kursining 12 ta mavzusini bazaga kiritish"

    def handle(self, *args, **options):
        created = 0
        updated = 0

        for topic_data in MTA_TOPICS:
            code = topic_data['code']
            order = TOPIC_ORDER.get(code, 99)

            topic, is_new = Topic.objects.update_or_create(
                code=code,
                defaults={
                    'title': topic_data['title'],
                    'description': topic_data['description'],
                    'order_number': order,
                    'pseudo_code': topic_data['pseudo_code'],
                    'real_code': topic_data['real_code'],
                    'code_language': topic_data['code_language'],
                    'visualization_type': topic_data['visualization_type'],
                    'lecture_duration': topic_data['lecture_duration'],
                    'is_published': True,  # Barcha mavzular nashr qilingan
                }
            )

            if is_new:
                created += 1
                self.stdout.write(self.style.SUCCESS(f"  [OK] Yaratildi: {code} - {topic_data['title'][:50]}"))
            else:
                updated += 1
                self.stdout.write(f"  [OK] Yangilandi: {code}")

        self.stdout.write("")
        self.stdout.write(self.style.SUCCESS(
            f"Tayyor! Yaratildi: {created}, Yangilandi: {updated} ta mavzu."
        ))
        self.stdout.write(
            "Endi: python manage.py createsuperuser → Admin orqali guruhlar va foydalanuvchilar yarating."
        )
